### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ajnovember**
New design, all current functionality working

### CODE REVIEW

**Comment by ruthmann** [comment]
Is this build live anywhere?

-Alex

On Wed, Jul 1, 2015 at 4:03 PM, ajnovember <notifications@github.com> wrote:

> New design, all current functionality working
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/NYUMusEdLab/groovePizza/pull/3
> Commit Summary
>
>    - RE #1, reorg js
>    - fixed mouseClick
>    - new design
>    - new design
>
> File Changes
>
>    - *M* css/GPstyle.css
>    <https://github.com/NYUMusEdLab/groovePizza/pull/3/files#diff-0> (71)
>    - *D* css/style.css
>    <https://github.com/NYUMusEdLab/groovePizza/pull/3/files#diff-1> (8)
>    - *A* imgs/steel.png
>    <https://github.com/NYUMusEdLab/groovePizza/pull/3/files#diff-2> (0)
>    - *A* imgs/toppings.png
>    <https://github.com/NYUMusEdLab/groovePizza/pull/3/files#diff-3> (0)
>    - *M* index.html
>    <https://github.com/NYUMusEdLab/groovePizza/pull/3/files#diff-4> (56)
>    - *M* js/GP.js
>    <https://github.com/NYUMusEdLab/groovePizza/pull/3/files#diff-5> (142)
>    - *M* js/visual.js
>    <https://github.com/NYUMusEdLab/groovePizza/pull/3/files#diff-6> (86)
>
> Patch Links:
>
>    - https://github.com/NYUMusEdLab/groovePizza/pull/3.patch
>    - https://github.com/NYUMusEdLab/groovePizza/pull/3.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NYUMusEdLab/groovePizza/pull/3>.
>



-- 


S. Alex Ruthmann, PhD

Co-Editor, *International Journal of Education & the Arts*
Past President, Association for Technology in Music Instruction
Guest Researcher, Institute of Cultural Industries, Shenzhen University
-------------------------------------------------
Associate Professor of Music Education and Music Technology
Department of Music and Performing Arts Professions
Steinhardt School of Culture, Education, and Human Development
New York University
-------------------------------------------------
Alex.Ruthmann@nyu.edu
Cell: +1 (734) 945-0679
Twitter: @alexruthmann


http://musedlab.org/
http://playwithyourmusic.org/
http://meetup.com/NYC-Music-Tech-Educator-Meetup/ (2nd Saturday of every
month)
http://www.alexruthmann.com/
http://performamatics.org/
http://www.ijea.org/

**Comment by kirlen** [comment]
reviewing now. @ajnovember this PR is going the wrong direction. Were you accidentally committing code directly to master?

**Comment by kirlen** [comment]
oh wait. scratch that.

**Comment by ajnovember** [comment]
@ruthmann yes just it up here http://adamnovember.com/groovePizza.html

**Pull request merged**
